import { Router } from 'express';
import { requireAdmin, requireAdminRoutePermission } from './auth';
import { registerAdminCommerceRoutes } from './routes/commerce-routes';
import { registerAdminPublicAuthRoutes, registerAdminSessionRoutes, } from './routes/auth-routes';
import { registerAdminContentRoutes } from './routes/content-routes';
import { registerAdminSystemRoutes } from './routes/system-routes';
export const adminRouter = Router();
registerAdminPublicAuthRoutes(adminRouter);
adminRouter.use(requireAdmin);
registerAdminSessionRoutes(adminRouter);
adminRouter.use(requireAdminRoutePermission);
registerAdminContentRoutes(adminRouter);
registerAdminCommerceRoutes(adminRouter);
registerAdminSystemRoutes(adminRouter);
