CREATE TABLE `user_stats` (
  `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` VARCHAR(191) NOT NULL COMMENT '用户 ID',
  `level` INT NOT NULL DEFAULT 1 COMMENT '等级',
  `title` VARCHAR(191) NULL COMMENT '等级头衔',
  `coins` DECIMAL(10,2) NOT NULL DEFAULT 0 COMMENT '余额快照',
  `win_rate` DOUBLE NOT NULL DEFAULT 0 COMMENT '竞猜胜率',
  `total_guess` INT NOT NULL DEFAULT 0 COMMENT '累计竞猜次数',
  `wins` INT NOT NULL DEFAULT 0 COMMENT '累计获胜次数',
  `followers` INT NOT NULL DEFAULT 0 COMMENT '粉丝数',
  `following` INT NOT NULL DEFAULT 0 COMMENT '关注数',
  `join_date` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '加入时间',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_stats_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户统计表';

