export type AdminPermissionAction = 'view' | 'create' | 'edit' | 'manage';

export interface AdminPermissionDefinition {
  code: string;
  name: string;
  module: string;
  action: AdminPermissionAction;
  parentCode?: string | null;
  sort: number;
  path?: string;
}

export const ADMIN_PERMISSION_DEFINITIONS: AdminPermissionDefinition[] = [
  {
    code: 'dashboard.view',
    name: '仪表盘',
    module: 'dashboard',
    action: 'view',
    sort: 100,
    path: '/dashboard',
  },
  {
    code: 'user.manage',
    name: '用户管理',
    module: 'user',
    action: 'manage',
    sort: 200,
  },
  {
    code: 'user.list.view',
    name: '用户列表',
    module: 'user',
    action: 'view',
    parentCode: 'user.manage',
    sort: 210,
    path: '/users/list',
  },
  {
    code: 'shop.manage',
    name: '店铺管理',
    module: 'shop',
    action: 'manage',
    sort: 300,
  },
  {
    code: 'shop.list.view',
    name: '店铺列表',
    module: 'shop',
    action: 'view',
    parentCode: 'shop.manage',
    sort: 310,
    path: '/shops/list',
  },
  {
    code: 'shop.apply.view',
    name: '开店审核',
    module: 'shop',
    action: 'view',
    parentCode: 'shop.manage',
    sort: 320,
    path: '/shops/apply',
  },
  {
    code: 'shop.products.view',
    name: '店铺商品',
    module: 'shop',
    action: 'view',
    parentCode: 'shop.manage',
    sort: 330,
    path: '/shops/products',
  },
  {
    code: 'brand.manage',
    name: '品牌管理',
    module: 'brand',
    action: 'manage',
    sort: 400,
  },
  {
    code: 'brand.list.view',
    name: '品牌管理',
    module: 'brand',
    action: 'view',
    parentCode: 'brand.manage',
    sort: 410,
    path: '/brands/list',
  },
  {
    code: 'product.manage',
    name: '商品管理',
    module: 'product',
    action: 'manage',
    sort: 500,
  },
  {
    code: 'product.list.view',
    name: '商品列表',
    module: 'product',
    action: 'view',
    parentCode: 'product.manage',
    sort: 510,
    path: '/products/list',
  },
  {
    code: 'product.brands.view',
    name: '品牌商品',
    module: 'product',
    action: 'view',
    parentCode: 'product.manage',
    sort: 520,
    path: '/products/brands',
  },
  {
    code: 'guess.manage',
    name: '竞猜管理',
    module: 'guess',
    action: 'manage',
    sort: 600,
  },
  {
    code: 'guess.list.view',
    name: '竞猜列表',
    module: 'guess',
    action: 'view',
    parentCode: 'guess.manage',
    sort: 610,
    path: '/guesses/list',
  },
  {
    code: 'guess.create.view',
    name: '创建竞猜',
    module: 'guess',
    action: 'view',
    parentCode: 'guess.manage',
    sort: 620,
    path: '/guesses/create',
  },
  {
    code: 'guess.friends.view',
    name: '好友竞猜',
    module: 'guess',
    action: 'view',
    parentCode: 'guess.manage',
    sort: 630,
    path: '/guesses/friends',
  },
  {
    code: 'guess.pk.view',
    name: 'PK 对战',
    module: 'guess',
    action: 'view',
    parentCode: 'guess.manage',
    sort: 640,
    path: '/pk',
  },
  {
    code: 'order.manage',
    name: '订单与履约',
    module: 'order',
    action: 'manage',
    sort: 700,
  },
  {
    code: 'order.list.view',
    name: '订单列表',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 710,
    path: '/orders/list',
  },
  {
    code: 'order.transactions.view',
    name: '交易流水',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 720,
    path: '/orders/transactions',
  },
  {
    code: 'order.logistics.view',
    name: '物流管理',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 730,
    path: '/orders/logistics',
  },
  {
    code: 'order.warehouse.virtual.view',
    name: '虚拟仓库',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 740,
    path: '/warehouse/virtual',
  },
  {
    code: 'order.warehouse.physical.view',
    name: '实体仓库',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 750,
    path: '/warehouse/physical',
  },
  {
    code: 'order.warehouse.consign.view',
    name: '寄售市场',
    module: 'order',
    action: 'view',
    parentCode: 'order.manage',
    sort: 760,
    path: '/warehouse/consign',
  },
  {
    code: 'marketing.manage',
    name: '营销中心',
    module: 'marketing',
    action: 'manage',
    sort: 800,
  },
  {
    code: 'marketing.equity.view',
    name: '权益金管理',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 810,
    path: '/equity',
  },
  {
    code: 'marketing.banners.view',
    name: '轮播管理',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 820,
    path: '/marketing/banners',
  },
  {
    code: 'marketing.coupons.view',
    name: '优惠券管理',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 830,
    path: '/marketing/coupons',
  },
  {
    code: 'marketing.checkin.view',
    name: '签到管理',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 840,
    path: '/marketing/checkin',
  },
  {
    code: 'marketing.invite.view',
    name: '邀请管理',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 850,
    path: '/marketing/invite',
  },
  {
    code: 'marketing.rankings.view',
    name: '排行榜配置',
    module: 'marketing',
    action: 'view',
    parentCode: 'marketing.manage',
    sort: 860,
    path: '/system/rankings',
  },
  {
    code: 'community.manage',
    name: '内容管理',
    module: 'community',
    action: 'manage',
    sort: 900,
  },
  {
    code: 'community.posts.view',
    name: '帖子管理',
    module: 'community',
    action: 'view',
    parentCode: 'community.manage',
    sort: 910,
    path: '/community/posts',
  },
  {
    code: 'community.comments.view',
    name: '评论管理',
    module: 'community',
    action: 'view',
    parentCode: 'community.manage',
    sort: 920,
    path: '/community/comments',
  },
  {
    code: 'community.reports.view',
    name: '举报处理',
    module: 'community',
    action: 'view',
    parentCode: 'community.manage',
    sort: 930,
    path: '/community/reports',
  },
  {
    code: 'community.live.list.view',
    name: '直播列表',
    module: 'community',
    action: 'view',
    parentCode: 'community.manage',
    sort: 940,
    path: '/live/list',
  },
  {
    code: 'community.chats.view',
    name: '聊天管理',
    module: 'community',
    action: 'view',
    parentCode: 'community.manage',
    sort: 950,
    path: '/system/chats',
  },
  {
    code: 'system.manage',
    name: '权限与系统',
    module: 'system',
    action: 'manage',
    sort: 1000,
  },
  {
    code: 'system.users.view',
    name: '系统用户',
    module: 'system',
    action: 'view',
    parentCode: 'system.manage',
    sort: 1010,
    path: '/system/users',
  },
  {
    code: 'system.roles.view',
    name: '角色管理',
    module: 'system',
    action: 'view',
    parentCode: 'system.manage',
    sort: 1020,
    path: '/system/roles',
  },
  {
    code: 'system.permissions.view',
    name: '权限管理',
    module: 'system',
    action: 'view',
    parentCode: 'system.manage',
    sort: 1030,
    path: '/users/permissions',
  },
  {
    code: 'system.categories.view',
    name: '分类管理',
    module: 'system',
    action: 'view',
    parentCode: 'system.manage',
    sort: 1040,
    path: '/system/categories',
  },
  {
    code: 'system.notifications.view',
    name: '通知管理',
    module: 'system',
    action: 'view',
    parentCode: 'system.manage',
    sort: 1050,
    path: '/system/notifications',
  },
];

export const ADMIN_MENU_PERMISSION_DEFINITIONS = ADMIN_PERMISSION_DEFINITIONS.filter(
  (item): item is AdminPermissionDefinition & { path: string } => Boolean(item.path),
);

export const ADMIN_PERMISSION_DEFINITION_BY_CODE = Object.fromEntries(
  ADMIN_PERMISSION_DEFINITIONS.map((item) => [item.code, item]),
) as Record<string, AdminPermissionDefinition>;

export const ADMIN_MENU_PERMISSION_BY_PATH = Object.fromEntries(
  ADMIN_MENU_PERMISSION_DEFINITIONS.map((item) => [item.path, item]),
) as Record<string, AdminPermissionDefinition & { path: string }>;

export function findAdminPermissionDefinitionByCode(code: string) {
  return ADMIN_PERMISSION_DEFINITION_BY_CODE[code] ?? null;
}

export function findAdminMenuPermissionByPath(path: string) {
  return ADMIN_MENU_PERMISSION_BY_PATH[path] ?? null;
}

export function getAdminPermissionChildren(parentCode: string) {
  return ADMIN_PERMISSION_DEFINITIONS.filter((item) => item.parentCode === parentCode);
}
