export const adminSchemas = {
    AdminLoginPayload: {
        type: 'object',
        required: ['username', 'password'],
        properties: {
            username: { type: 'string', example: 'admin_root' },
            password: { type: 'string', example: '123456' },
        },
    },
    AdminRoleItem: {
        type: 'object',
        required: ['id', 'code', 'name'],
        properties: {
            id: { type: 'string', example: '1' },
            code: { type: 'string', example: 'super_admin' },
            name: { type: 'string', example: '超级管理员' },
        },
    },
    AdminProfile: {
        type: 'object',
        required: ['id', 'username', 'displayName', 'status', 'roles', 'permissions', 'permissionModules'],
        properties: {
            id: { type: 'string', example: '1' },
            username: { type: 'string', example: 'admin_root' },
            displayName: { type: 'string', example: 'JOY 管理员' },
            phoneNumber: { type: 'string', nullable: true, example: '13800138000' },
            email: { type: 'string', nullable: true, example: 'admin@example.com' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            roles: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminRoleItem' },
            },
            permissions: {
                type: 'array',
                items: { type: 'string' },
                example: ['dashboard.view', 'user.manage'],
            },
            permissionModules: {
                type: 'array',
                items: { type: 'string' },
                example: ['仪表盘', '用户管理', '角色管理'],
            },
        },
    },
    UpdateUserBanPayload: {
        type: 'object',
        required: ['banned'],
        properties: {
            banned: { type: 'boolean', example: true },
        },
    },
    UserListResult: {
        type: 'object',
        required: ['items', 'total', 'page', 'pageSize', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/UserSummary' },
            },
            total: { type: 'integer', example: 326 },
            page: { type: 'integer', example: 1 },
            pageSize: { type: 'integer', example: 20 },
            summary: {
                type: 'object',
                required: ['totalUsers', 'verifiedUsers', 'bannedUsers'],
                properties: {
                    totalUsers: { type: 'integer', example: 326 },
                    verifiedUsers: { type: 'integer', example: 48 },
                    bannedUsers: { type: 'integer', example: 3 },
                },
            },
        },
    },
    PaginatedGuessListResult: {
        type: 'object',
        required: ['items', 'total', 'page', 'pageSize'],
        properties: {
            items: {
                type: 'array',
                items: { type: 'object', additionalProperties: true },
            },
            total: { type: 'integer', example: 42 },
            page: { type: 'integer', example: 1 },
            pageSize: { type: 'integer', example: 10 },
        },
    },
    PaginatedOrderListResult: {
        type: 'object',
        required: ['items', 'total', 'page', 'pageSize'],
        properties: {
            items: {
                type: 'array',
                items: { type: 'object', additionalProperties: true },
            },
            total: { type: 'integer', example: 18 },
            page: { type: 'integer', example: 1 },
            pageSize: { type: 'integer', example: 10 },
        },
    },
    AdminChangePasswordPayload: {
        type: 'object',
        required: ['currentPassword', 'newPassword'],
        properties: {
            currentPassword: { type: 'string', example: '123456' },
            newPassword: { type: 'string', example: '654321' },
        },
    },
    AdminCommunityPostItem: {
        type: 'object',
        required: [
            'id',
            'title',
            'content',
            'tag',
            'type',
            'typeLabel',
            'scope',
            'scopeLabel',
            'authorId',
            'authorUid',
            'authorName',
            'guessId',
            'guessTitle',
            'images',
            'likeCount',
            'commentCount',
            'repostCount',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '5001' },
            title: { type: 'string', nullable: true, example: '今天这双会不会继续涨' },
            content: { type: 'string', example: '感觉这波还有空间。' },
            tag: { type: 'string', nullable: true, example: '球鞋' },
            type: {
                type: 'string',
                enum: ['post', 'guess', 'repost'],
                example: 'guess',
            },
            typeLabel: { type: 'string', example: '竞猜动态' },
            scope: {
                type: 'string',
                enum: ['public', 'followers', 'private', 'unknown'],
                example: 'public',
            },
            scopeLabel: { type: 'string', example: '公开' },
            authorId: { type: 'string', example: '1001' },
            authorUid: { type: 'string', nullable: true, example: 'DOACgEkT' },
            authorName: { type: 'string', example: '乐事不服榜' },
            guessId: { type: 'string', nullable: true, example: '901' },
            guessTitle: { type: 'string', nullable: true, example: 'Panda 本周会不会继续涨价' },
            images: {
                type: 'array',
                items: { type: 'string', example: 'https://example.com/post-1.png' },
            },
            likeCount: { type: 'integer', example: 18 },
            commentCount: { type: 'integer', example: 6 },
            repostCount: { type: 'integer', example: 2 },
            createdAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T09:30:00.000Z',
            },
            updatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T10:00:00.000Z',
            },
        },
    },
    AdminCommunityPostListResult: {
        type: 'object',
        required: ['items'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCommunityPostItem' },
            },
        },
    },
    DeleteAdminCommunityPostResult: {
        type: 'object',
        required: ['id', 'success'],
        properties: {
            id: { type: 'string', example: '5001' },
            success: { type: 'boolean', example: true },
        },
    },
    AdminCommunityCommentItem: {
        type: 'object',
        required: [
            'id',
            'targetType',
            'targetPostId',
            'targetPostTitle',
            'parentId',
            'content',
            'authorId',
            'authorUid',
            'authorName',
            'likeCount',
            'replyCount',
            'createdAt',
        ],
        properties: {
            id: { type: 'string', example: '7001' },
            targetType: { type: 'string', enum: ['post'], example: 'post' },
            targetPostId: { type: 'string', nullable: true, example: '5001' },
            targetPostTitle: { type: 'string', nullable: true, example: '今天这双会不会继续涨' },
            parentId: { type: 'string', nullable: true, example: null },
            content: { type: 'string', example: '我觉得还会涨。' },
            authorId: { type: 'string', example: '1002' },
            authorUid: { type: 'string', nullable: true, example: 'UGhde902' },
            authorName: { type: 'string', example: '鞋柜研究所' },
            likeCount: { type: 'integer', example: 5 },
            replyCount: { type: 'integer', example: 1 },
            createdAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T11:00:00.000Z',
            },
        },
    },
    AdminCommunityCommentListResult: {
        type: 'object',
        required: ['items'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCommunityCommentItem' },
            },
        },
    },
    DeleteAdminCommunityCommentResult: {
        type: 'object',
        required: ['id', 'success'],
        properties: {
            id: { type: 'string', example: '7001' },
            success: { type: 'boolean', example: true },
        },
    },
    AdminCommunityReportItem: {
        type: 'object',
        required: [
            'id',
            'reporterUserId',
            'reporterUid',
            'reporterName',
            'targetType',
            'targetId',
            'targetTitle',
            'targetContent',
            'targetAuthorId',
            'targetAuthorUid',
            'targetAuthorName',
            'reasonType',
            'reasonLabel',
            'reasonDetail',
            'status',
            'statusLabel',
            'handleAction',
            'handleActionLabel',
            'handleNote',
            'handledAt',
            'createdAt',
        ],
        properties: {
            id: { type: 'string', example: '9001' },
            reporterUserId: { type: 'string', example: '1003' },
            reporterUid: { type: 'string', nullable: true, example: 'X9kd02Qa' },
            reporterName: { type: 'string', example: '举报用户' },
            targetType: { type: 'string', enum: ['post'], example: 'post' },
            targetId: { type: 'string', example: '5001' },
            targetTitle: { type: 'string', nullable: true, example: '今天这双会不会继续涨' },
            targetContent: { type: 'string', nullable: true, example: '感觉这波还有空间。' },
            targetAuthorId: { type: 'string', nullable: true, example: '1001' },
            targetAuthorUid: { type: 'string', nullable: true, example: 'DOACgEkT' },
            targetAuthorName: { type: 'string', nullable: true, example: '乐事不服榜' },
            reasonType: {
                type: 'string',
                enum: ['spam', 'explicit', 'abuse', 'false_info', 'other'],
                example: 'spam',
            },
            reasonLabel: { type: 'string', example: '垃圾广告' },
            reasonDetail: { type: 'string', nullable: true, example: '反复发外链导流' },
            status: {
                type: 'string',
                enum: ['pending', 'reviewing', 'resolved', 'rejected'],
                example: 'pending',
            },
            statusLabel: { type: 'string', example: '待处理' },
            handleAction: {
                anyOf: [
                    {
                        type: 'string',
                        enum: ['approve', 'reject', 'ban'],
                    },
                    { type: 'null' },
                ],
            },
            handleActionLabel: { type: 'string', nullable: true, example: '采纳' },
            handleNote: { type: 'string', nullable: true, example: null },
            handledAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            createdAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T12:00:00.000Z',
            },
        },
    },
    AdminCommunityReportListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCommunityReportItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'pending', 'reviewing', 'resolved', 'rejected'],
                properties: {
                    total: { type: 'integer', example: 15 },
                    pending: { type: 'integer', example: 4 },
                    reviewing: { type: 'integer', example: 2 },
                    resolved: { type: 'integer', example: 7 },
                    rejected: { type: 'integer', example: 2 },
                },
            },
        },
    },
    UpdateAdminCommunityReportPayload: {
        type: 'object',
        required: ['action'],
        properties: {
            action: {
                type: 'string',
                enum: ['review', 'approve', 'reject', 'ban'],
                example: 'approve',
            },
            note: { type: 'string', nullable: true, example: '确认违规，已处理' },
        },
    },
    UpdateAdminCommunityReportResult: {
        type: 'object',
        required: ['item'],
        properties: {
            item: { $ref: '#/components/schemas/AdminCommunityReportItem' },
        },
    },
    AdminLiveRoomItem: {
        type: 'object',
        required: [
            'id',
            'title',
            'imageUrl',
            'hostId',
            'hostUid',
            'hostName',
            'rawStatusCode',
            'status',
            'statusLabel',
            'startTime',
            'guessCount',
            'currentGuessTitle',
            'participantCount',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '3001' },
            title: { type: 'string', example: '今晚聊聊球鞋行情' },
            imageUrl: { type: 'string', nullable: true, example: 'https://example.com/live-cover.png' },
            hostId: { type: 'string', nullable: true, example: '1001' },
            hostUid: { type: 'string', nullable: true, example: 'DOACgEkT' },
            hostName: { type: 'string', example: '乐事不服榜' },
            rawStatusCode: { type: 'integer', nullable: true, example: 10 },
            status: {
                type: 'string',
                enum: ['live', 'upcoming', 'ended'],
                example: 'live',
            },
            statusLabel: { type: 'string', example: '直播中' },
            startTime: {
                type: 'string',
                format: 'date-time',
                nullable: true,
                example: '2026-04-21T20:00:00.000Z',
            },
            guessCount: { type: 'integer', example: 2 },
            currentGuessTitle: { type: 'string', nullable: true, example: 'Panda 本周会不会继续涨价' },
            participantCount: { type: 'integer', example: 128 },
            createdAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T18:00:00.000Z',
            },
            updatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T20:30:00.000Z',
            },
        },
    },
    AdminLiveRoomListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminLiveRoomItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'live', 'upcoming', 'ended'],
                properties: {
                    total: { type: 'integer', example: 6 },
                    live: { type: 'integer', example: 2 },
                    upcoming: { type: 'integer', example: 1 },
                    ended: { type: 'integer', example: 3 },
                },
            },
        },
    },
    StopAdminLiveRoomResult: {
        type: 'object',
        required: ['item'],
        properties: {
            item: { $ref: '#/components/schemas/AdminLiveRoomItem' },
        },
    },
    AdminCategoryItem: {
        type: 'object',
        required: [
            'id',
            'bizType',
            'bizTypeCode',
            'bizTypeLabel',
            'level',
            'name',
            'sort',
            'status',
            'statusLabel',
            'usageCount',
            'usageBreakdown',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '12' },
            bizType: {
                type: 'string',
                enum: ['brand', 'shop', 'product', 'guess', 'unknown'],
                example: 'product',
            },
            bizTypeCode: { type: 'integer', enum: [10, 20, 30, 40], example: 30 },
            bizTypeLabel: { type: 'string', example: '商品分类' },
            parentId: { type: 'string', nullable: true, example: '9' },
            parentName: { type: 'string', nullable: true, example: '食品饮料' },
            level: { type: 'integer', example: 2 },
            path: { type: 'string', nullable: true, example: '9/12' },
            name: { type: 'string', example: '膨化零食' },
            iconUrl: { type: 'string', nullable: true, example: 'https://example.com/icon.png' },
            description: { type: 'string', nullable: true, example: '平台商品分类' },
            sort: { type: 'integer', example: 10 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            statusLabel: { type: 'string', example: '启用' },
            usageCount: { type: 'integer', example: 18 },
            usageBreakdown: {
                type: 'object',
                required: ['brands', 'brandProducts', 'shops', 'shopApplies', 'guesses'],
                properties: {
                    brands: { type: 'integer', example: 0 },
                    brandProducts: { type: 'integer', example: 18 },
                    shops: { type: 'integer', example: 0 },
                    shopApplies: { type: 'integer', example: 0 },
                    guesses: { type: 'integer', example: 0 },
                },
            },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-19T10:30:00.000Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-19T12:00:00.000Z' },
        },
    },
    AdminCategoryListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCategoryItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'disabled', 'byBizType'],
                properties: {
                    total: { type: 'integer', example: 32 },
                    active: { type: 'integer', example: 29 },
                    disabled: { type: 'integer', example: 3 },
                    byBizType: { type: 'object', additionalProperties: { type: 'integer' } },
                },
            },
        },
    },
    CreateAdminCategoryPayload: {
        type: 'object',
        required: ['bizTypeCode', 'name'],
        properties: {
            bizTypeCode: { type: 'integer', enum: [10, 20, 30, 40], example: 30 },
            parentId: { type: 'string', nullable: true, example: '9' },
            name: { type: 'string', example: '膨化零食' },
            iconUrl: { type: 'string', nullable: true, example: 'https://example.com/icon.png' },
            description: { type: 'string', nullable: true, example: '平台商品分类' },
            sort: { type: 'integer', example: 10 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    UpdateAdminCategoryPayload: {
        type: 'object',
        required: ['name'],
        properties: {
            name: { type: 'string', example: '膨化零食' },
            iconUrl: { type: 'string', nullable: true, example: 'https://example.com/icon.png' },
            description: { type: 'string', nullable: true, example: '平台商品分类' },
            sort: { type: 'integer', example: 10 },
        },
    },
    UpdateAdminCategoryStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminCategoryResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '12' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    AdminRankingSummaryItem: {
        type: 'object',
        required: [
            'id',
            'boardType',
            'boardTypeLabel',
            'periodType',
            'periodTypeLabel',
            'periodValue',
            'periodLabel',
            'entryCount',
            'topUserId',
            'topUserName',
            'topUserUid',
            'topScore',
            'topValue',
            'generatedAt',
        ],
        properties: {
            id: { type: 'string', example: 'guessWins:daily:20260421' },
            boardType: {
                type: 'string',
                enum: ['guessWins', 'winRate', 'inviteCount'],
                example: 'guessWins',
            },
            boardTypeLabel: { type: 'string', example: '猜中次数榜' },
            periodType: {
                type: 'string',
                enum: ['daily', 'weekly', 'monthly', 'allTime'],
                example: 'daily',
            },
            periodTypeLabel: { type: 'string', example: '日榜' },
            periodValue: { type: 'string', example: '20260421' },
            periodLabel: { type: 'string', example: '2026-04-21' },
            entryCount: { type: 'integer', example: 50 },
            topUserId: { type: 'string', nullable: true, example: '101' },
            topUserName: { type: 'string', nullable: true, example: '乐事不服榜' },
            topUserUid: { type: 'string', nullable: true, example: 'DOACgEkT' },
            topScore: { type: 'number', example: 28 },
            topValue: { type: 'string', example: '28场' },
            generatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T10:15:00.000Z',
            },
        },
    },
    AdminRankingListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminRankingSummaryItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'guessWins', 'winRate', 'inviteCount'],
                properties: {
                    total: { type: 'integer', example: 18 },
                    guessWins: { type: 'integer', example: 6 },
                    winRate: { type: 'integer', example: 6 },
                    inviteCount: { type: 'integer', example: 6 },
                },
            },
        },
    },
    AdminRankingEntryItem: {
        type: 'object',
        required: [
            'rank',
            'userId',
            'userUid',
            'nickname',
            'avatar',
            'level',
            'score',
            'value',
            'extraSummary',
        ],
        properties: {
            rank: { type: 'integer', example: 1 },
            userId: { type: 'string', example: '101' },
            userUid: { type: 'string', nullable: true, example: 'DOACgEkT' },
            nickname: { type: 'string', example: '乐事不服榜' },
            avatar: { type: 'string', nullable: true, example: 'https://example.com/avatar.png' },
            level: { type: 'integer', example: 6 },
            score: { type: 'number', example: 28 },
            value: { type: 'string', example: '28场' },
            extraSummary: { type: 'string', nullable: true, example: '最长连胜 6 场' },
        },
    },
    AdminRankingDetailResult: {
        type: 'object',
        required: [
            'boardType',
            'boardTypeLabel',
            'periodType',
            'periodTypeLabel',
            'periodValue',
            'periodLabel',
            'generatedAt',
            'totalEntries',
            'items',
        ],
        properties: {
            boardType: {
                type: 'string',
                enum: ['guessWins', 'winRate', 'inviteCount'],
                example: 'guessWins',
            },
            boardTypeLabel: { type: 'string', example: '猜中次数榜' },
            periodType: {
                type: 'string',
                enum: ['daily', 'weekly', 'monthly', 'allTime'],
                example: 'daily',
            },
            periodTypeLabel: { type: 'string', example: '日榜' },
            periodValue: { type: 'string', example: '20260421' },
            periodLabel: { type: 'string', example: '2026-04-21' },
            generatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T10:15:00.000Z',
            },
            totalEntries: { type: 'integer', example: 50 },
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminRankingEntryItem' },
            },
        },
    },
    RefreshAdminRankingItem: {
        type: 'object',
        required: ['boardType', 'periodType', 'periodValue', 'entryCount', 'generatedAt'],
        properties: {
            boardType: {
                type: 'string',
                enum: ['guessWins', 'winRate', 'inviteCount'],
                example: 'guessWins',
            },
            periodType: {
                type: 'string',
                enum: ['daily', 'weekly', 'monthly', 'allTime'],
                example: 'daily',
            },
            periodValue: { type: 'string', example: '20260421' },
            entryCount: { type: 'integer', example: 50 },
            generatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-22T08:30:00.000Z',
            },
        },
    },
    RefreshAdminRankingsPayload: {
        type: 'object',
        properties: {
            boardType: {
                type: 'string',
                nullable: true,
                enum: ['guessWins', 'winRate', 'inviteCount'],
                example: 'guessWins',
            },
            periodType: {
                type: 'string',
                nullable: true,
                enum: ['daily', 'weekly', 'monthly', 'allTime'],
                example: 'daily',
            },
            periodValue: {
                type: 'string',
                nullable: true,
                example: '20260421',
            },
        },
    },
    RefreshAdminRankingsResult: {
        type: 'object',
        required: ['items'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/RefreshAdminRankingItem' },
            },
        },
    },
    CancelAdminConsignResult: {
        type: 'object',
        required: ['id', 'physicalItemId', 'status', 'canceledAt'],
        properties: {
            id: { type: 'string', example: '301' },
            physicalItemId: { type: 'string', nullable: true, example: '9001' },
            status: {
                type: 'string',
                enum: ['canceled'],
                example: 'canceled',
            },
            canceledAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-22T08:30:00.000Z',
            },
        },
    },
    UpdateAdminSystemUserStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminSystemUserStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '1' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    AdminPermissionItem: {
        type: 'object',
        required: [
            'id',
            'code',
            'name',
            'module',
            'action',
            'status',
            'sort',
            'assignedRoleCount',
            'isBuiltIn',
        ],
        properties: {
            id: { type: 'string', example: '11' },
            code: { type: 'string', example: 'user.manage' },
            name: { type: 'string', example: '查看用户' },
            module: { type: 'string', example: '用户管理' },
            action: {
                type: 'string',
                enum: ['view', 'create', 'edit', 'manage', 'unknown'],
                example: 'view',
            },
            parentId: { type: 'string', nullable: true, example: '10' },
            parentName: { type: 'string', nullable: true, example: '用户管理' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            sort: { type: 'integer', example: 10 },
            assignedRoleCount: { type: 'integer', example: 3 },
            isBuiltIn: { type: 'boolean', example: true },
        },
    },
    AdminPermissionListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminPermissionItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'disabled', 'modules'],
                properties: {
                    total: { type: 'integer', example: 24 },
                    active: { type: 'integer', example: 20 },
                    disabled: { type: 'integer', example: 4 },
                    modules: { type: 'integer', example: 6 },
                },
            },
        },
    },
    UpdateAdminPermissionStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminPermissionStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '11' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    CreateAdminPermissionPayload: {
        type: 'object',
        required: ['code', 'name', 'module', 'action'],
        properties: {
            code: { type: 'string', example: 'user.manage' },
            name: { type: 'string', example: '查看用户' },
            module: { type: 'string', example: '用户管理' },
            action: {
                type: 'string',
                enum: ['view', 'create', 'edit', 'manage'],
                example: 'view',
            },
            parentId: { type: 'string', nullable: true, example: '10' },
            sort: { type: 'integer', example: 10 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    UpdateAdminPermissionPayload: {
        type: 'object',
        required: ['code', 'name', 'module', 'action'],
        properties: {
            code: { type: 'string', example: 'user.manage' },
            name: { type: 'string', example: '查看用户' },
            module: { type: 'string', example: '用户管理' },
            action: {
                type: 'string',
                enum: ['view', 'create', 'edit', 'manage'],
                example: 'view',
            },
            parentId: { type: 'string', nullable: true, example: '10' },
            sort: { type: 'integer', example: 10 },
        },
    },
    AdminPermissionMutationResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '11' },
        },
    },
    CreateAdminSystemUserPayload: {
        type: 'object',
        required: ['username', 'password', 'displayName', 'roleIds'],
        properties: {
            username: { type: 'string', example: 'ops_manager' },
            password: { type: 'string', example: '123456' },
            displayName: { type: 'string', example: '运营经理' },
            phoneNumber: { type: 'string', nullable: true, example: '13800138000' },
            email: { type: 'string', nullable: true, example: 'ops@example.com' },
            roleIds: {
                type: 'array',
                items: { type: 'string', example: '2' },
            },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    UpdateAdminSystemUserPayload: {
        type: 'object',
        required: ['username', 'displayName', 'roleIds'],
        properties: {
            username: { type: 'string', example: 'ops_manager' },
            displayName: { type: 'string', example: '运营经理' },
            phoneNumber: { type: 'string', nullable: true, example: '13800138000' },
            email: { type: 'string', nullable: true, example: 'ops@example.com' },
            roleIds: {
                type: 'array',
                items: { type: 'string', example: '2' },
            },
        },
    },
    ResetAdminSystemUserPasswordPayload: {
        type: 'object',
        required: ['newPassword'],
        properties: {
            newPassword: { type: 'string', example: '654321' },
        },
    },
    AdminSystemUserMutationResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '3' },
        },
    },
    UpdateAdminRoleStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminRoleStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '2' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    CreateAdminRolePayload: {
        type: 'object',
        required: ['code', 'name'],
        properties: {
            code: { type: 'string', example: 'ops_manager' },
            name: { type: 'string', example: '运营经理' },
            description: { type: 'string', nullable: true, example: '负责活动与内容运营' },
            sort: { type: 'integer', example: 20 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    CreateAdminRoleResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '2' },
        },
    },
    UpdateAdminRolePayload: {
        type: 'object',
        required: ['code', 'name'],
        properties: {
            code: { type: 'string', example: 'ops_manager' },
            name: { type: 'string', example: '运营经理' },
            description: { type: 'string', nullable: true, example: '负责活动与内容运营' },
            sort: { type: 'integer', example: 20 },
        },
    },
    UpdateAdminRoleResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '2' },
        },
    },
    AdminRoleListItem: {
        type: 'object',
        required: [
            'id',
            'code',
            'name',
            'permissionRange',
            'memberCount',
            'permissionCount',
            'status',
            'isSystem',
            'sort',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '2' },
            code: { type: 'string', example: 'ops_manager' },
            name: { type: 'string', example: '运营经理' },
            description: { type: 'string', nullable: true, example: '负责活动与内容运营' },
            permissionRange: { type: 'string', example: '用户 / 订单 等 3 个模块' },
            permissionModules: {
                type: 'array',
                items: { type: 'string', example: '用户' },
            },
            memberCount: { type: 'integer', example: 6 },
            permissionCount: { type: 'integer', example: 18 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            isSystem: { type: 'boolean', example: false },
            sort: { type: 'integer', example: 20 },
            createdAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-20T08:30:00.000Z',
            },
            updatedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-20T10:15:00.000Z',
            },
        },
    },
    AdminRoleListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminRoleListItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'disabled', 'members'],
                properties: {
                    total: { type: 'integer', example: 5 },
                    active: { type: 'integer', example: 4 },
                    disabled: { type: 'integer', example: 1 },
                    members: { type: 'integer', example: 23 },
                },
            },
        },
    },
    UpdateAdminRolePermissionsPayload: {
        type: 'object',
        required: ['permissionIds'],
        properties: {
            permissionIds: {
                type: 'array',
                items: { type: 'string', example: '11' },
            },
        },
    },
    UpdateAdminRolePermissionsResult: {
        type: 'object',
        required: ['id', 'permissionIds'],
        properties: {
            id: { type: 'string', example: '2' },
            permissionIds: {
                type: 'array',
                items: { type: 'string', example: '11' },
            },
        },
    },
    CreateAdminNotificationPayload: {
        type: 'object',
        required: ['title', 'content', 'type', 'audience'],
        properties: {
            title: { type: 'string', example: '系统维护通知' },
            content: { type: 'string', example: '今晚 23:00-23:30 进行系统维护，请提前保存操作。' },
            type: {
                type: 'string',
                enum: ['system', 'order', 'guess', 'social'],
                example: 'system',
            },
            audience: {
                type: 'string',
                enum: ['all_users', 'order_users', 'guess_users', 'post_users', 'chat_users'],
                example: 'all_users',
            },
            actionUrl: { type: 'string', nullable: true, example: '/orders' },
        },
    },
    CreateAdminNotificationResult: {
        type: 'object',
        required: ['sentCount'],
        properties: {
            sentCount: { type: 'integer', example: 1280 },
        },
    },
    AdminNotificationItem: {
        type: 'object',
        required: [
            'id',
            'title',
            'audience',
            'type',
            'status',
            'targetType',
            'recipientCount',
            'readCount',
            'unreadCount',
            'createdAt',
            'sentAt',
        ],
        properties: {
            id: { type: 'string', example: '6d5b8f7f' },
            title: { type: 'string', example: '系统维护通知' },
            content: { type: 'string', nullable: true, example: '今晚 23:00-23:30 进行系统维护。' },
            audience: {
                type: 'string',
                enum: ['all_users', 'order_users', 'guess_users', 'post_users', 'chat_users', 'targeted_users'],
                example: 'all_users',
            },
            type: {
                type: 'string',
                enum: ['system', 'order', 'guess', 'social'],
                example: 'system',
            },
            status: { type: 'string', enum: ['sent'], example: 'sent' },
            targetType: {
                type: 'string',
                enum: ['order', 'guess', 'post', 'chat', 'unknown'],
                example: 'unknown',
            },
            targetId: { type: 'string', nullable: true, example: '1024' },
            actionUrl: { type: 'string', nullable: true, example: '/orders/list' },
            recipientCount: { type: 'integer', example: 1280 },
            readCount: { type: 'integer', example: 512 },
            unreadCount: { type: 'integer', example: 768 },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-21T08:00:00.000Z' },
            sentAt: { type: 'string', format: 'date-time', example: '2026-04-21T08:00:00.000Z' },
        },
    },
    AdminNotificationListResult: {
        type: 'object',
        required: ['items', 'total', 'page', 'pageSize', 'summary', 'basis'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminNotificationItem' },
            },
            total: { type: 'integer', example: 236 },
            page: { type: 'integer', example: 1 },
            pageSize: { type: 'integer', example: 10 },
            summary: {
                type: 'object',
                required: ['total', 'sent', 'read', 'unread'],
                properties: {
                    total: { type: 'integer', example: 236 },
                    sent: { type: 'integer', example: 18620 },
                    read: { type: 'integer', example: 9210 },
                    unread: { type: 'integer', example: 9410 },
                },
            },
            basis: {
                type: 'string',
                example: '基于 notification 真表按消息载荷聚合为发送批次视图；搜索、筛选和分页都建立在真实批次全集上。',
            },
        },
    },
    AdminChatItem: {
        type: 'object',
        required: ['id', 'userA', 'userB', 'messages', 'unreadMessages', 'riskLevel', 'status', 'updatedAt'],
        properties: {
            id: { type: 'string', example: '12:103' },
            userA: {
                type: 'object',
                required: ['id', 'uid', 'name'],
                properties: {
                    id: { type: 'string', example: '12' },
                    uid: { type: 'string', nullable: true, example: 'DOACgEkT' },
                    name: { type: 'string', example: '小零' },
                },
            },
            userB: {
                type: 'object',
                required: ['id', 'uid', 'name'],
                properties: {
                    id: { type: 'string', example: '103' },
                    uid: { type: 'string', nullable: true, example: 'ABC123XY' },
                    name: { type: 'string', example: '乐事不服榜' },
                },
            },
            messages: { type: 'integer', example: 26 },
            unreadMessages: { type: 'integer', example: 3 },
            riskLevel: { type: 'string', enum: ['low', 'medium', 'high'], example: 'medium' },
            status: { type: 'string', enum: ['normal', 'review', 'escalated'], example: 'review' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-21T08:30:00.000Z' },
        },
    },
    AdminChatListResult: {
        type: 'object',
        required: ['items', 'summary', 'basis'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminChatItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'review', 'escalated', 'highRisk'],
                properties: {
                    total: { type: 'integer', example: 92 },
                    review: { type: 'integer', example: 15 },
                    escalated: { type: 'integer', example: 3 },
                    highRisk: { type: 'integer', example: 3 },
                },
            },
            basis: {
                type: 'string',
                example: '基于 chat_message 真表按用户对聚合唯一会话，风险等级取双方 user.risk_level 的较高值；当前没有 admin 聊天抽检专表。',
            },
        },
    },
    AdminChatDetailResult: {
        type: 'object',
        required: ['conversation', 'messages', 'basis'],
        properties: {
            conversation: {
                type: 'object',
                required: ['id', 'userA', 'userB', 'messages', 'unreadMessages', 'riskLevel', 'status', 'updatedAt'],
                properties: {
                    id: { type: 'string', example: '12:103' },
                    userA: {
                        type: 'object',
                        required: ['id', 'uid', 'name', 'riskLevel'],
                        properties: {
                            id: { type: 'string', example: '12' },
                            uid: { type: 'string', nullable: true, example: 'DOACgEkT' },
                            name: { type: 'string', example: '小零' },
                            riskLevel: { type: 'string', enum: ['low', 'medium', 'high'], example: 'low' },
                        },
                    },
                    userB: {
                        type: 'object',
                        required: ['id', 'uid', 'name', 'riskLevel'],
                        properties: {
                            id: { type: 'string', example: '103' },
                            uid: { type: 'string', nullable: true, example: 'ABC123XY' },
                            name: { type: 'string', example: '乐事不服榜' },
                            riskLevel: { type: 'string', enum: ['low', 'medium', 'high'], example: 'medium' },
                        },
                    },
                    messages: { type: 'integer', example: 26 },
                    unreadMessages: { type: 'integer', example: 3 },
                    riskLevel: { type: 'string', enum: ['low', 'medium', 'high'], example: 'medium' },
                    status: { type: 'string', enum: ['normal', 'review', 'escalated'], example: 'review' },
                    updatedAt: { type: 'string', format: 'date-time', example: '2026-04-21T08:30:00.000Z' },
                },
            },
            messages: {
                type: 'array',
                items: {
                    type: 'object',
                    required: ['id', 'senderId', 'senderName', 'receiverId', 'receiverName', 'content', 'read', 'createdAt'],
                    properties: {
                        id: { type: 'string', example: '8001' },
                        senderId: { type: 'string', example: '12' },
                        senderName: { type: 'string', example: '小零' },
                        receiverId: { type: 'string', example: '103' },
                        receiverName: { type: 'string', example: '乐事不服榜' },
                        content: { type: 'string', example: '这单什么时候发货？' },
                        read: { type: 'boolean', example: false },
                        createdAt: { type: 'string', format: 'date-time', example: '2026-04-21T08:00:00.000Z' },
                    },
                },
            },
            basis: {
                type: 'string',
                example: '基于 chat_message 真表返回会话消息时间线；管理后台详情读取不会修改已读状态或会话摘要。',
            },
        },
    },
    UpdateAdminShopStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'paused', 'closed'],
                example: 'paused',
            },
        },
    },
    UpdateAdminShopStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '12' },
            status: {
                type: 'string',
                enum: ['active', 'paused', 'closed'],
                example: 'paused',
            },
        },
    },
    UpdateAdminShopProductStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'off_shelf'],
                example: 'off_shelf',
            },
        },
    },
    UpdateAdminShopProductStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '501' },
            status: {
                type: 'string',
                enum: ['active', 'off_shelf'],
                example: 'active',
            },
        },
    },
    AdminEquityAccountItem: {
        type: 'object',
        required: [
            'id',
            'userId',
            'userName',
            'phoneNumber',
            'avatarUrl',
            'categoryAmount',
            'exchangeAmount',
            'generalAmount',
            'totalBalance',
            'totalGranted',
            'totalUsed',
            'totalExpired',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '1' },
            userId: { type: 'string', example: '1001' },
            userName: { type: 'string', nullable: true, example: '张三' },
            phoneNumber: { type: 'string', nullable: true, example: '13800138000' },
            avatarUrl: { type: 'string', nullable: true, example: 'https://example.com/avatar.png' },
            categoryAmount: { type: 'integer', example: 12800, description: '单位：分' },
            exchangeAmount: { type: 'integer', example: 5600, description: '单位：分' },
            generalAmount: { type: 'integer', example: 3200, description: '单位：分' },
            totalBalance: { type: 'integer', example: 21600, description: '单位：分' },
            totalGranted: { type: 'integer', example: 48000, description: '单位：分' },
            totalUsed: { type: 'integer', example: 22400, description: '单位：分' },
            totalExpired: { type: 'integer', example: 4000, description: '单位：分' },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-20T08:00:00.000Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-20T12:00:00.000Z' },
        },
    },
    AdminEquityLogItem: {
        type: 'object',
        required: [
            'id',
            'accountId',
            'userId',
            'type',
            'subType',
            'amount',
            'balance',
            'sourceType',
            'refId',
            'note',
            'expireAt',
            'createdAt',
        ],
        properties: {
            id: { type: 'string', example: '3001' },
            accountId: { type: 'string', example: '1' },
            userId: { type: 'string', example: '1001' },
            type: {
                type: 'string',
                enum: ['grant', 'use', 'expire', 'adjust', 'unknown'],
                example: 'adjust',
            },
            subType: {
                type: 'string',
                nullable: true,
                enum: ['category', 'exchange', 'general'],
                example: 'category',
            },
            amount: { type: 'integer', example: -1200, description: '单位：分' },
            balance: { type: 'integer', example: 20400, description: '单位：分' },
            sourceType: { type: 'integer', nullable: true, example: 40 },
            refId: { type: 'string', nullable: true, example: '5001' },
            note: { type: 'string', nullable: true, example: '后台手工扣减过期权益' },
            expireAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-20T12:00:00.000Z' },
        },
    },
    AdminEquityListResult: {
        type: 'object',
        required: ['items', 'total', 'page', 'pageSize', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminEquityAccountItem' },
            },
            total: { type: 'integer', example: 28 },
            page: { type: 'integer', example: 1 },
            pageSize: { type: 'integer', example: 10 },
            summary: {
                type: 'object',
                required: ['totalAccounts', 'totalGranted', 'totalUsed', 'totalExpired', 'activeBalance'],
                properties: {
                    totalAccounts: { type: 'integer', example: 28 },
                    totalGranted: { type: 'integer', example: 1280000, description: '单位：分' },
                    totalUsed: { type: 'integer', example: 432000, description: '单位：分' },
                    totalExpired: { type: 'integer', example: 56000, description: '单位：分' },
                    activeBalance: { type: 'integer', example: 792000, description: '单位：分' },
                },
            },
        },
    },
    AdminEquityDetailResult: {
        type: 'object',
        required: ['account', 'logs'],
        properties: {
            account: { $ref: '#/components/schemas/AdminEquityAccountItem' },
            logs: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminEquityLogItem' },
            },
        },
    },
    AdjustAdminEquityPayload: {
        type: 'object',
        required: ['userId', 'subType', 'amount'],
        properties: {
            userId: { type: 'string', example: '1001' },
            subType: {
                type: 'string',
                enum: ['category', 'exchange', 'general'],
                example: 'category',
            },
            amount: { type: 'integer', example: -1200, description: '单位：分；正数增加，负数扣减' },
            note: { type: 'string', nullable: true, example: '后台手工扣减过期权益' },
        },
    },
    AdjustAdminEquityResult: {
        type: 'object',
        required: ['account', 'log'],
        properties: {
            account: { $ref: '#/components/schemas/AdminEquityAccountItem' },
            log: { $ref: '#/components/schemas/AdminEquityLogItem' },
        },
    },
    AdminBannerItem: {
        type: 'object',
        required: [
            'id',
            'position',
            'positionLabel',
            'title',
            'subtitle',
            'imageUrl',
            'targetType',
            'targetTypeLabel',
            'targetId',
            'targetName',
            'actionUrl',
            'sort',
            'rawStatus',
            'status',
            'statusLabel',
            'startAt',
            'endAt',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '8' },
            position: { type: 'string', example: 'home_hero' },
            positionLabel: { type: 'string', example: '首页轮播' },
            title: { type: 'string', example: 'Panda 限时竞猜季' },
            subtitle: { type: 'string', nullable: true, example: '本周热门话题' },
            imageUrl: { type: 'string', example: 'https://example.com/banner.png' },
            targetType: {
                type: 'string',
                enum: ['guess', 'post', 'product', 'shop', 'page', 'external'],
                example: 'guess',
            },
            targetTypeLabel: { type: 'string', example: '竞猜' },
            targetId: { type: 'string', nullable: true, example: '901' },
            targetName: { type: 'string', nullable: true, example: 'Panda 本周会不会继续涨价' },
            actionUrl: { type: 'string', nullable: true, example: null },
            sort: { type: 'integer', example: 100 },
            rawStatus: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            status: {
                type: 'string',
                enum: ['active', 'scheduled', 'paused', 'ended'],
                example: 'active',
            },
            statusLabel: {
                type: 'string',
                enum: ['投放中', '待排期', '已暂停', '已结束'],
                example: '投放中',
            },
            startAt: {
                type: 'string',
                format: 'date-time',
                nullable: true,
                example: '2026-04-20T08:00:00.000Z',
            },
            endAt: {
                type: 'string',
                format: 'date-time',
                nullable: true,
                example: '2026-04-30T23:59:59.000Z',
            },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-20T08:00:00.000Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-20T12:00:00.000Z' },
        },
    },
    AdminBannerListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminBannerItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'scheduled', 'paused', 'ended'],
                properties: {
                    total: { type: 'integer', example: 6 },
                    active: { type: 'integer', example: 3 },
                    scheduled: { type: 'integer', example: 1 },
                    paused: { type: 'integer', example: 1 },
                    ended: { type: 'integer', example: 1 },
                },
            },
        },
    },
    CreateAdminBannerPayload: {
        type: 'object',
        required: ['position', 'title', 'imageUrl', 'targetType'],
        properties: {
            position: { type: 'string', example: 'home_hero' },
            title: { type: 'string', example: 'Panda 限时竞猜季' },
            subtitle: { type: 'string', nullable: true, example: '本周热门话题' },
            imageUrl: { type: 'string', example: 'https://example.com/banner.png' },
            targetType: {
                type: 'string',
                enum: ['guess', 'post', 'product', 'shop', 'page', 'external'],
                example: 'guess',
            },
            targetId: { type: 'string', nullable: true, example: '901' },
            actionUrl: { type: 'string', nullable: true, example: null },
            sort: { type: 'integer', example: 100 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            startAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            endAt: { type: 'string', format: 'date-time', nullable: true, example: null },
        },
    },
    CreateAdminBannerResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '8' },
        },
    },
    UpdateAdminBannerPayload: {
        type: 'object',
        required: ['position', 'title', 'imageUrl', 'targetType'],
        properties: {
            position: { type: 'string', example: 'home_hero' },
            title: { type: 'string', example: 'Panda 限时竞猜季' },
            subtitle: { type: 'string', nullable: true, example: '本周热门话题' },
            imageUrl: { type: 'string', example: 'https://example.com/banner.png' },
            targetType: {
                type: 'string',
                enum: ['guess', 'post', 'product', 'shop', 'page', 'external'],
                example: 'guess',
            },
            targetId: { type: 'string', nullable: true, example: '901' },
            actionUrl: { type: 'string', nullable: true, example: null },
            sort: { type: 'integer', example: 100 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            startAt: { type: 'string', format: 'date-time', nullable: true, example: null },
            endAt: { type: 'string', format: 'date-time', nullable: true, example: null },
        },
    },
    UpdateAdminBannerResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '8' },
        },
    },
    UpdateAdminBannerStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminBannerStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '8' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    DeleteAdminBannerResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '8' },
        },
    },
    AdminCheckinRewardConfigItem: {
        type: 'object',
        required: [
            'id',
            'dayNo',
            'rewardType',
            'rewardTypeLabel',
            'rewardValue',
            'sort',
            'status',
            'statusLabel',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '1501' },
            dayNo: { type: 'integer', example: 1 },
            rewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coin',
            },
            rewardTypeLabel: { type: 'string', example: '零食币' },
            rewardValue: { type: 'integer', example: 10 },
            rewardRefId: { type: 'string', nullable: true, example: '601' },
            title: { type: 'string', nullable: true, example: '第 7 天大奖' },
            sort: { type: 'integer', example: 7 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            statusLabel: { type: 'string', example: '启用' },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-20T08:00:00.000Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-20T12:00:00.000Z' },
        },
    },
    AdminCheckinRewardConfigListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCheckinRewardConfigItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'disabled'],
                properties: {
                    total: { type: 'integer', example: 7 },
                    active: { type: 'integer', example: 6 },
                    disabled: { type: 'integer', example: 1 },
                },
            },
        },
    },
    CreateAdminCheckinRewardConfigPayload: {
        type: 'object',
        required: ['dayNo', 'rewardType', 'rewardValue'],
        properties: {
            dayNo: { type: 'integer', minimum: 1, maximum: 365, example: 7 },
            rewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coupon',
            },
            rewardValue: { type: 'integer', minimum: 1, example: 1 },
            rewardRefId: { type: 'string', nullable: true, example: '601' },
            title: { type: 'string', nullable: true, example: '第 7 天大奖' },
            sort: { type: 'integer', minimum: 0, example: 7 },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    CreateAdminCheckinRewardConfigResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '1508' },
        },
    },
    UpdateAdminCheckinRewardConfigPayload: {
        type: 'object',
        required: ['dayNo', 'rewardType', 'rewardValue'],
        properties: {
            dayNo: { type: 'integer', minimum: 1, maximum: 365, example: 7 },
            rewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coupon',
            },
            rewardValue: { type: 'integer', minimum: 1, example: 1 },
            rewardRefId: { type: 'string', nullable: true, example: '601' },
            title: { type: 'string', nullable: true, example: '第 7 天大奖' },
            sort: { type: 'integer', minimum: 0, example: 7 },
        },
    },
    UpdateAdminCheckinRewardConfigResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '1508' },
        },
    },
    UpdateAdminCheckinRewardConfigStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    UpdateAdminCheckinRewardConfigStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '1508' },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'disabled',
            },
        },
    },
    AdminInviteRewardConfigItem: {
        type: 'object',
        required: [
            'id',
            'inviterRewardType',
            'inviterRewardTypeLabel',
            'inviterRewardValue',
            'inviteeRewardType',
            'inviteeRewardTypeLabel',
            'inviteeRewardValue',
            'status',
            'statusLabel',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '1601' },
            inviterRewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coin',
            },
            inviterRewardTypeLabel: { type: 'string', example: '零食币' },
            inviterRewardValue: { type: 'integer', example: 50 },
            inviterRewardRefId: { type: 'string', nullable: true, example: null },
            inviteeRewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coin',
            },
            inviteeRewardTypeLabel: { type: 'string', example: '零食币' },
            inviteeRewardValue: { type: 'integer', example: 30 },
            inviteeRewardRefId: { type: 'string', nullable: true, example: null },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
            statusLabel: { type: 'string', example: '启用' },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-19T03:48:33.870Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-19T03:48:33.870Z' },
        },
    },
    AdminInviteRecordItem: {
        type: 'object',
        required: [
            'id',
            'inviterId',
            'inviterName',
            'inviteeId',
            'inviteeName',
            'registeredAt',
        ],
        properties: {
            id: { type: 'string', example: '103' },
            inviterId: { type: 'string', example: '101' },
            inviterName: { type: 'string', example: '用户 101' },
            inviterPhone: { type: 'string', nullable: true, example: '18800000001' },
            inviterUidCode: { type: 'string', nullable: true, example: 'JOYU0101' },
            inviteCode: { type: 'string', nullable: true, example: 'INVITE101' },
            inviteeId: { type: 'string', example: '103' },
            inviteeName: { type: 'string', example: '用户 103' },
            inviteePhone: { type: 'string', nullable: true, example: '18800000003' },
            inviteeUidCode: { type: 'string', nullable: true, example: 'JOYU0103' },
            registeredAt: { type: 'string', format: 'date-time', example: '2026-04-13T17:00:00.000Z' },
        },
    },
    AdminInviteRecordListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminInviteRecordItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'distinctInviters'],
                properties: {
                    total: { type: 'integer', example: 2 },
                    distinctInviters: { type: 'integer', example: 1 },
                },
            },
        },
    },
    UpdateAdminInviteRewardConfigPayload: {
        type: 'object',
        required: [
            'inviterRewardType',
            'inviterRewardValue',
            'inviteeRewardType',
            'inviteeRewardValue',
            'status',
        ],
        properties: {
            inviterRewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coin',
            },
            inviterRewardValue: { type: 'integer', minimum: 1, example: 50 },
            inviterRewardRefId: { type: 'string', nullable: true, example: null },
            inviteeRewardType: {
                type: 'string',
                enum: ['coin', 'coupon', 'physical'],
                example: 'coin',
            },
            inviteeRewardValue: { type: 'integer', minimum: 1, example: 30 },
            inviteeRewardRefId: { type: 'string', nullable: true, example: null },
            status: {
                type: 'string',
                enum: ['active', 'disabled'],
                example: 'active',
            },
        },
    },
    UpdateAdminInviteRewardConfigResult: {
        type: 'object',
        required: ['item'],
        properties: {
            item: { $ref: '#/components/schemas/AdminInviteRewardConfigItem' },
        },
    },
    AdminCouponTemplateItem: {
        type: 'object',
        required: [
            'id',
            'code',
            'name',
            'type',
            'typeLabel',
            'rawStatus',
            'status',
            'statusLabel',
            'scopeType',
            'scopeTypeLabel',
            'sourceType',
            'sourceTypeLabel',
            'minAmount',
            'discountAmount',
            'maxDiscountAmount',
            'validityType',
            'validityTypeLabel',
            'validDays',
            'totalQuantity',
            'userLimit',
            'grantedCount',
            'remainingQuantity',
            'batchCount',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '601' },
            code: { type: 'string', example: 'TPLABC123DEF' },
            name: { type: 'string', example: '新客满减券' },
            type: {
                type: 'string',
                enum: ['cash', 'discount', 'shipping'],
                example: 'cash',
            },
            typeLabel: { type: 'string', example: '满减券' },
            rawStatus: {
                type: 'string',
                enum: ['active', 'paused', 'disabled'],
                example: 'active',
            },
            status: {
                type: 'string',
                enum: ['active', 'scheduled', 'paused', 'disabled', 'ended'],
                example: 'active',
            },
            statusLabel: { type: 'string', example: '启用' },
            scopeType: {
                type: 'string',
                enum: ['platform', 'shop'],
                example: 'shop',
            },
            scopeTypeLabel: { type: 'string', example: '指定店铺' },
            shopId: { type: 'string', nullable: true, example: '401' },
            shopName: { type: 'string', nullable: true, example: 'Joy Select' },
            description: { type: 'string', nullable: true, example: '新客活动优惠券' },
            sourceType: {
                type: 'string',
                enum: ['admin', 'activity', 'compensation', 'system'],
                example: 'admin',
            },
            sourceTypeLabel: { type: 'string', example: '后台人工' },
            minAmount: { type: 'integer', example: 5000, description: '单位：分' },
            discountAmount: { type: 'integer', example: 1000, description: '单位：分' },
            discountRate: { type: 'number', nullable: true, example: 8.5 },
            maxDiscountAmount: { type: 'integer', example: 0, description: '单位：分' },
            validityType: {
                type: 'string',
                enum: ['fixed', 'relative'],
                example: 'fixed',
            },
            validityTypeLabel: { type: 'string', example: '固定时间段' },
            startAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-04-20T00:00:00.000Z' },
            endAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-12-31T23:59:59.000Z' },
            validDays: { type: 'integer', example: 0 },
            totalQuantity: { type: 'integer', example: 100, description: '-1 表示不限' },
            userLimit: { type: 'integer', example: 1 },
            grantedCount: { type: 'integer', example: 12 },
            remainingQuantity: { type: 'integer', nullable: true, example: 88 },
            batchCount: { type: 'integer', example: 2 },
            lastBatchAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-04-20T10:00:00.000Z' },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-19T03:48:33.852Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-20T12:00:00.000Z' },
        },
    },
    AdminCouponListResult: {
        type: 'object',
        required: ['items', 'summary'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCouponTemplateItem' },
            },
            summary: {
                type: 'object',
                required: ['total', 'active', 'scheduled', 'paused', 'disabled', 'ended'],
                properties: {
                    total: { type: 'integer', example: 12 },
                    active: { type: 'integer', example: 6 },
                    scheduled: { type: 'integer', example: 2 },
                    paused: { type: 'integer', example: 1 },
                    disabled: { type: 'integer', example: 2 },
                    ended: { type: 'integer', example: 1 },
                },
            },
        },
    },
    AdminCouponGrantBatchItem: {
        type: 'object',
        required: [
            'id',
            'batchNo',
            'sourceType',
            'sourceTypeLabel',
            'targetUserCount',
            'grantedCount',
            'status',
            'statusLabel',
            'createdAt',
            'updatedAt',
        ],
        properties: {
            id: { type: 'string', example: '611' },
            batchNo: { type: 'string', example: 'BCHABC123DEF' },
            templateId: { type: 'string', nullable: true, example: '601' },
            sourceType: {
                type: 'string',
                enum: ['admin', 'activity', 'compensation', 'system'],
                example: 'admin',
            },
            sourceTypeLabel: { type: 'string', example: '后台人工' },
            operatorId: { type: 'string', nullable: true, example: '1' },
            operatorName: { type: 'string', nullable: true, example: '系统管理员' },
            targetUserCount: { type: 'integer', example: 120 },
            grantedCount: { type: 'integer', example: 118 },
            status: {
                type: 'string',
                enum: ['pending', 'processing', 'completed', 'failed'],
                example: 'completed',
            },
            statusLabel: { type: 'string', example: '已完成' },
            note: { type: 'string', nullable: true, example: '针对首单用户发放' },
            createdAt: { type: 'string', format: 'date-time', example: '2026-04-20T08:00:00.000Z' },
            updatedAt: { type: 'string', format: 'date-time', example: '2026-04-20T08:00:05.000Z' },
        },
    },
    AdminCouponGrantBatchListResult: {
        type: 'object',
        required: ['items'],
        properties: {
            items: {
                type: 'array',
                items: { $ref: '#/components/schemas/AdminCouponGrantBatchItem' },
            },
        },
    },
    CreateAdminCouponTemplatePayload: {
        type: 'object',
        required: [
            'name',
            'type',
            'scopeType',
            'minAmount',
            'validityType',
            'totalQuantity',
            'userLimit',
        ],
        properties: {
            name: { type: 'string', example: '新客满减券' },
            type: {
                type: 'string',
                enum: ['cash', 'discount', 'shipping'],
                example: 'cash',
            },
            scopeType: {
                type: 'string',
                enum: ['platform', 'shop'],
                example: 'shop',
            },
            shopId: { type: 'string', nullable: true, example: '401' },
            description: { type: 'string', nullable: true, example: '新客活动优惠券' },
            minAmount: { type: 'integer', example: 5000, description: '单位：分' },
            discountAmount: { type: 'integer', example: 1000, description: '单位：分' },
            discountRate: { type: 'number', nullable: true, example: 8.5 },
            maxDiscountAmount: { type: 'integer', nullable: true, example: 0, description: '单位：分' },
            validityType: {
                type: 'string',
                enum: ['fixed', 'relative'],
                example: 'fixed',
            },
            startAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-04-20T00:00:00.000Z' },
            endAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-12-31T23:59:59.000Z' },
            validDays: { type: 'integer', nullable: true, example: 7 },
            totalQuantity: { type: 'integer', example: 100, description: '-1 表示不限' },
            userLimit: { type: 'integer', example: 1 },
            status: {
                type: 'string',
                enum: ['active', 'paused', 'disabled'],
                example: 'active',
            },
        },
    },
    CreateAdminCouponTemplateResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '602' },
        },
    },
    UpdateAdminCouponTemplatePayload: {
        type: 'object',
        required: [
            'name',
            'type',
            'scopeType',
            'minAmount',
            'validityType',
            'totalQuantity',
            'userLimit',
        ],
        properties: {
            name: { type: 'string', example: '新客满减券' },
            type: {
                type: 'string',
                enum: ['cash', 'discount', 'shipping'],
                example: 'cash',
            },
            scopeType: {
                type: 'string',
                enum: ['platform', 'shop'],
                example: 'shop',
            },
            shopId: { type: 'string', nullable: true, example: '401' },
            description: { type: 'string', nullable: true, example: '新客活动优惠券' },
            minAmount: { type: 'integer', example: 5000, description: '单位：分' },
            discountAmount: { type: 'integer', example: 1000, description: '单位：分' },
            discountRate: { type: 'number', nullable: true, example: 8.5 },
            maxDiscountAmount: { type: 'integer', nullable: true, example: 0, description: '单位：分' },
            validityType: {
                type: 'string',
                enum: ['fixed', 'relative'],
                example: 'fixed',
            },
            startAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-04-20T00:00:00.000Z' },
            endAt: { type: 'string', format: 'date-time', nullable: true, example: '2026-12-31T23:59:59.000Z' },
            validDays: { type: 'integer', nullable: true, example: 7 },
            totalQuantity: { type: 'integer', example: 100, description: '-1 表示不限' },
            userLimit: { type: 'integer', example: 1 },
            status: {
                type: 'string',
                enum: ['active', 'paused', 'disabled'],
                example: 'active',
            },
        },
    },
    UpdateAdminCouponTemplateResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '602' },
        },
    },
    UpdateAdminCouponTemplateStatusPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['active', 'paused', 'disabled'],
                example: 'paused',
            },
        },
    },
    UpdateAdminCouponTemplateStatusResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '602' },
            status: {
                type: 'string',
                enum: ['active', 'paused', 'disabled'],
                example: 'paused',
            },
        },
    },
    CreateAdminCouponGrantBatchPayload: {
        type: 'object',
        required: ['audience'],
        properties: {
            audience: {
                type: 'string',
                enum: ['all_users', 'order_users', 'guess_users', 'shop_users'],
                example: 'all_users',
            },
            note: { type: 'string', nullable: true, example: '针对首单用户发放' },
        },
    },
    CreateAdminCouponGrantBatchResult: {
        type: 'object',
        required: ['id', 'grantedCount'],
        properties: {
            id: { type: 'string', example: '612' },
            grantedCount: { type: 'integer', example: 88 },
        },
    },
    ReviewAdminShopApplyPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
            rejectReason: { type: 'string', nullable: true, example: '资质信息不完整' },
        },
    },
    ReviewAdminShopApplyResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '18' },
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
        },
    },
    ReviewAdminGuessPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
            rejectReason: { type: 'string', nullable: true, example: '竞猜描述信息不完整' },
        },
    },
    ShipAdminOrderPayload: {
        type: 'object',
        required: ['shippingType'],
        properties: {
            shippingType: {
                type: 'string',
                enum: ['express', 'same_city', 'self_pickup'],
                example: 'express',
            },
            trackingNo: { type: 'string', nullable: true, example: 'SF1234567890' },
        },
    },
    ShipAdminOrderResult: {
        type: 'object',
        required: ['id', 'fulfillmentId', 'fulfillmentStatus', 'shippingType', 'trackingNo', 'shippedAt'],
        properties: {
            id: { type: 'string', example: '1201' },
            fulfillmentId: { type: 'string', example: '5001' },
            fulfillmentStatus: { type: 'string', enum: ['shipped'], example: 'shipped' },
            shippingType: {
                type: 'string',
                enum: ['express', 'same_city', 'self_pickup'],
                example: 'express',
            },
            trackingNo: { type: 'string', nullable: true, example: 'SF1234567890' },
            shippedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T10:30:00.000Z',
            },
        },
    },
    DeliverAdminLogisticsPayload: {
        type: 'object',
        properties: {},
    },
    DeliverAdminLogisticsResult: {
        type: 'object',
        required: ['id', 'orderId', 'status', 'completedAt'],
        properties: {
            id: { type: 'string', example: '5001' },
            orderId: { type: 'string', example: '1201' },
            status: { type: 'string', enum: ['completed'], example: 'completed' },
            completedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-22T10:40:00.000Z',
            },
        },
    },
    ReviewAdminOrderRefundPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
            reviewNote: { type: 'string', nullable: true, example: '退款原因属实，同意退款' },
        },
    },
    ReviewAdminOrderRefundResult: {
        type: 'object',
        required: ['id', 'refundId', 'status', 'reviewedAt'],
        properties: {
            id: { type: 'string', example: '1201' },
            refundId: { type: 'string', example: '7001' },
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
            reviewedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T10:35:00.000Z',
            },
        },
    },
    CompleteAdminOrderRefundPayload: {
        type: 'object',
        properties: {},
    },
    CompleteAdminOrderRefundResult: {
        type: 'object',
        required: ['id', 'refundId', 'status', 'completedAt'],
        properties: {
            id: { type: 'string', example: '1201' },
            refundId: { type: 'string', example: '7001' },
            status: { type: 'string', enum: ['completed'], example: 'completed' },
            completedAt: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-21T11:00:00.000Z',
            },
        },
    },
    CreateAdminGuessPayload: {
        type: 'object',
        required: ['title', 'categoryId', 'productId', 'endTime', 'optionTexts'],
        properties: {
            title: { type: 'string', example: '乐事和奥利奥谁更受欢迎？' },
            categoryId: { type: 'string', example: '18' },
            productId: { type: 'string', example: '502' },
            endTime: {
                type: 'string',
                format: 'date-time',
                example: '2026-04-23T10:00:00.000Z',
            },
            description: {
                type: 'string',
                nullable: true,
                example: '围绕热门零食做一场二选一竞猜',
            },
            imageUrl: {
                type: 'string',
                nullable: true,
                example: 'https://example.com/guess-cover.png',
            },
            optionTexts: {
                type: 'array',
                minItems: 2,
                items: { type: 'string', example: '乐事' },
                example: ['乐事', '奥利奥'],
            },
        },
    },
    CreateAdminGuessResult: {
        type: 'object',
        required: ['id', 'status', 'reviewStatus'],
        properties: {
            id: { type: 'string', example: '301' },
            status: { type: 'string', enum: ['active'], example: 'active' },
            reviewStatus: { type: 'string', enum: ['approved'], example: 'approved' },
        },
    },
    ReviewAdminGuessResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '301' },
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
        },
    },
    CreateAdminBrandPayload: {
        type: 'object',
        required: ['name', 'categoryId'],
        properties: {
            name: { type: 'string', example: '耐克' },
            categoryId: { type: 'string', example: '12' },
            contactName: { type: 'string', nullable: true, example: '张三' },
            contactPhone: { type: 'string', nullable: true, example: '13800138000' },
            description: { type: 'string', nullable: true, example: '运动品牌' },
            status: { type: 'string', enum: ['active', 'disabled'], example: 'active' },
        },
    },
    CreateAdminBrandResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '22' },
        },
    },
    UpdateAdminBrandPayload: {
        type: 'object',
        required: ['name', 'categoryId', 'status'],
        properties: {
            name: { type: 'string', example: '耐克' },
            categoryId: { type: 'string', example: '12' },
            contactName: { type: 'string', nullable: true, example: '张三' },
            contactPhone: { type: 'string', nullable: true, example: '13800138000' },
            description: { type: 'string', nullable: true, example: '运动品牌' },
            status: { type: 'string', enum: ['active', 'disabled'], example: 'active' },
        },
    },
    UpdateAdminBrandResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '22' },
        },
    },
    CreateAdminBrandProductPayload: {
        type: 'object',
        required: ['brandId', 'name', 'categoryId', 'guidePrice'],
        properties: {
            brandId: { type: 'string', example: '22' },
            name: { type: 'string', example: 'Air Max 270' },
            categoryId: { type: 'string', example: '31' },
            guidePrice: { type: 'integer', example: 69900 },
            supplyPrice: { type: 'integer', nullable: true, example: 42000 },
            defaultImg: { type: 'string', nullable: true, example: 'https://example.com/shoe.png' },
            description: { type: 'string', nullable: true, example: '品牌标准商品' },
            status: { type: 'string', enum: ['active', 'disabled'], example: 'active' },
        },
    },
    CreateAdminBrandProductResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '108' },
        },
    },
    UpdateAdminBrandProductPayload: {
        type: 'object',
        required: ['brandId', 'name', 'categoryId', 'guidePrice', 'status'],
        properties: {
            brandId: { type: 'string', example: '22' },
            name: { type: 'string', example: 'Air Max 270' },
            categoryId: { type: 'string', example: '31' },
            guidePrice: { type: 'integer', example: 69900 },
            supplyPrice: { type: 'integer', nullable: true, example: 42000 },
            defaultImg: { type: 'string', nullable: true, example: 'https://example.com/shoe.png' },
            description: { type: 'string', nullable: true, example: '品牌标准商品' },
            status: { type: 'string', enum: ['active', 'disabled'], example: 'active' },
        },
    },
    UpdateAdminBrandProductResult: {
        type: 'object',
        required: ['id'],
        properties: {
            id: { type: 'string', example: '108' },
        },
    },
    ReviewAdminBrandAuthApplyPayload: {
        type: 'object',
        required: ['status'],
        properties: {
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
            rejectReason: { type: 'string', nullable: true, example: '授权资料不完整' },
        },
    },
    ReviewAdminBrandAuthApplyResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '31' },
            status: {
                type: 'string',
                enum: ['approved', 'rejected'],
                example: 'approved',
            },
        },
    },
    RevokeAdminBrandAuthRecordResult: {
        type: 'object',
        required: ['id', 'status'],
        properties: {
            id: { type: 'string', example: '48' },
            status: {
                type: 'string',
                enum: ['revoked'],
                example: 'revoked',
            },
        },
    },
};
