export const commonSchemas = {
  UserSummary: {
    type: 'object',
    required: ['id', 'uid', 'phone', 'name', 'role'],
    properties: {
      id: { type: 'string', example: '1001' },
      uid: { type: 'string', example: 'aZkLmNqP' },
      phone: { type: 'string', example: '13800138000' },
      name: { type: 'string', example: '优米用户' },
      role: {
        type: 'string',
        enum: ['user', 'admin', 'shop_owner'],
        example: 'shop_owner',
      },
      banned: { type: 'boolean', example: false },
      avatar: { type: 'string', nullable: true, example: 'https://example.com/avatar.png' },
      level: { type: 'integer', example: 6 },
      title: { type: 'string', nullable: true, example: '潮流猜手' },
      signature: { type: 'string', nullable: true, example: '今天也要上分' },
      gender: { type: 'string', nullable: true, example: 'male' },
      birthday: { type: 'string', nullable: true, format: 'date', example: '1998-06-18' },
      region: { type: 'string', nullable: true, example: 'Shanghai' },
      shopName: { type: 'string', nullable: true, example: 'Umi Select' },
      worksPrivacy: {
        type: 'string',
        enum: ['all', 'friends', 'me'],
        example: 'friends',
      },
      favPrivacy: {
        type: 'string',
        enum: ['all', 'me'],
        example: 'me',
      },
      followers: { type: 'integer', example: 128 },
      following: { type: 'integer', example: 42 },
      totalOrders: { type: 'integer', example: 123 },
      winRate: { type: 'number', example: 62.5 },
      totalGuess: { type: 'integer', example: 48 },
      wins: { type: 'integer', example: 30 },
      joinDate: {
        type: 'string',
        nullable: true,
        format: 'date-time',
        example: '2026-04-19T10:30:00.000Z',
      },
      shopVerified: { type: 'boolean', example: true },
    },
  },
} as const;
